apiVersion: v1
appVersion: v1.9.9
description: Chart for Postwoman
home: https://github.com/csycsy2510316/helm-chart/tree/master/helm-chart-sources/postwoman-helm-chart
maintainers:
- email: csycsy2510316@163.com
  name: hepeng
name: postwoman
version: 1.0.0
keywords:
- web
- http
- web
- test
- api
sources:
- https://registry.hub.docker.com/r/liyasthomas/postwoman
- https://github.com/hoppscotch/hoppscotch